/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmConfigServer.java
 *
 * Created on Sep 11, 2011, 1:06:01 AM
 */
package geraarquivos.view;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;

/**
 *
 * @author tiagoendreskochenborger
 */
public class FrmConexoes extends javax.swing.JFrame {

    
    java.util.ResourceBundle properties = java.util.ResourceBundle.getBundle("resources/Config"); // NOI18N
        
    /** Creates new form FrmConfigServer */
    public FrmConexoes() {
       
        //Captura o valor da propriedade, através do nome da propriedade(Key)
        tfServer.setText(properties.getString("server"));
        ftPorta.setText(properties.getString("porta"));
        tfUsuario.setText(properties.getString("login"));
        pfSenha.setText(properties.getString("senha"));
        tfNomeBanco.setText(properties.getString("database"));
        
        //System.out.println(tfServer.getText() + "\n" + ftPorta.getText() + "\n" + tfUsuario.getText() + "\n" + pfSenha.getText() + "\n" + tfNomeBanco.getText());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Porta = new javax.swing.JLabel();
        tfServer = new javax.swing.JTextField();
        ftPorta = new javax.swing.JFormattedTextField();
        tfUsuario = new javax.swing.JTextField();
        tfNomeBanco = new javax.swing.JTextField();
        pfSenha = new javax.swing.JPasswordField();
        cbTipo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        btSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("titulos/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("FrmConfigServer.jLabel1.text_1_1")); // NOI18N

        jLabel2.setText(bundle.getString("FrmConfigServer.jLabel2.text_1_1")); // NOI18N

        jLabel3.setText(bundle.getString("FrmConfigServer.jLabel3.text_1_1")); // NOI18N

        jLabel4.setText(bundle.getString("FrmConfigServer.jLabel4.text_1_1")); // NOI18N

        Porta.setText(bundle.getString("FrmConfigServer.Porta.text_1_1")); // NOI18N

        ftPorta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####"))));

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mysql", "Oracle", "MSSQL" }));

        jLabel6.setText(bundle.getString("FrmConfigServer.jLabel6.text_1_1")); // NOI18N
        jLabel6.setToolTipText(bundle.getString("FrmConexoes.jLabel6.toolTipText")); // NOI18N

        jCheckBox1.setText(bundle.getString("FrmConfigServer.jCheckBox1.text")); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(17, 17, 17)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(jLabel1)
                    .add(jLabel2)
                    .add(jLabel3)
                    .add(jLabel6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(cbTipo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(tfNomeBanco, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                            .add(pfSenha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(23, 23, 23))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, tfUsuario, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, tfServer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(Porta)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(ftPorta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jCheckBox1))
                        .add(8, 8, 8))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(0, 20, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cbTipo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(Porta)
                    .add(tfServer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ftPorta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(tfUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jCheckBox1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(pfSenha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(tfNomeBanco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(26, 26, 26))
        );

        jLabel1.getAccessibleContext().setAccessibleName(bundle.getString("FrmConfigServer.jLabel1.text_1")); // NOI18N
        jLabel2.getAccessibleContext().setAccessibleName(bundle.getString("FrmConfigServer.jLabel2")); // NOI18N
        jLabel3.getAccessibleContext().setAccessibleName(bundle.getString("Senha")); // NOI18N
        jLabel4.getAccessibleContext().setAccessibleName(bundle.getString("NomeBanco")); // NOI18N
        Porta.getAccessibleContext().setAccessibleName(bundle.getString("FrmConfigServer.Porta.AccessibleContext.accessibleName")); // NOI18N
        jLabel6.getAccessibleContext().setAccessibleName(bundle.getString("Banco")); // NOI18N

        btSalvar.setText(bundle.getString("FrmConfigServer.btSalvar.text_1")); // NOI18N
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(btSalvar)
                        .add(210, 210, 210)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btSalvar)
                .add(15, 15, 15))
        );

        jPanel1.getAccessibleContext().setAccessibleName(bundle.getString("Usuario")); // NOI18N
        btSalvar.getAccessibleContext().setAccessibleName(bundle.getString("Salvar")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        
            // o arquivo encontra-se no mesmo diretório //da aplicação  
            File file = new File("resources/Config.properties");      
            Properties props = new Properties();  
            FileInputStream fis = null;  
            try {  
                fis = new FileInputStream(file);  
                //lê os dados que estão no arquivo  
                props.load(fis);    
                fis.close();  
            }  
            catch (IOException ex) {  
                System.out.println(ex.getMessage());  
                ex.printStackTrace();  
            }
            
            
            props.setProperty("server",tfServer.getText());
            props.setProperty("porta",ftPorta.getText());
            props.setProperty("usuario",tfUsuario.getText());
            props.setProperty("senha",pfSenha.getPassword().toString());
            props.setProperty("database",tfNomeBanco.getText());
            //convertendo o item selecionado em texto
            props.setProperty("banco", (String) cbTipo.getSelectedItem());
            
            //o arquivo encontra-se no mesmo diretório da aplicação  
            FileOutputStream fos = null;  
            try {  
                fos = new FileOutputStream(file);  
                //grava os dados  no arquivo  
                props.store(fos, "Configurações salvas");    
                fos.close();  
            }  
            catch (IOException ex) {  
                System.out.println(ex.getMessage());  
                ex.printStackTrace();  
            }
            
            
            dispose();
            
        
    }//GEN-LAST:event_btSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmConexoes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Porta;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cbTipo;
    private javax.swing.JFormattedTextField ftPorta;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField tfNomeBanco;
    private javax.swing.JTextField tfServer;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
